#ifndef CONSTANTS_H_INCLUDED
#define CONSTANTS_H_INCLUDED

#define BANQUISE_CASES (BANQUISE_SIZE * BANQUISE_SIZE)
#define BANQUISE_SIZE 10
#define NB_FLAKES 3
#define NB_ROCKS 4
#define NB_SPRINGS 1
#define NB_TRAPS 1
#define NB_HAMMERS 2
#define NB_WATER 6
#define NB_OF_COORDINATES 2
#define PERCENT 101



#endif // CONSTANTS_H_INCLUDED
